GET http://localhost:4000/products?1limit HTTP/1.1

### product add 

POST http://localhost:4000/product/add HTTP/1.1
content-type: application/json

{   
    
    "name":"Iphone 15",
    "brand_id":2000,
    "category_id": 1000,
    "created_date":"2023-03-03",
    "description":"New IPHONE",
    "sale":10,
    "price":1222,
    "stock":122,
    "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/1667px-Apple_logo_black.svg.png"
    }

### user req

GET http://localhost:4000/users?limit=3 HTTP/1.1

### user add 

POST http://localhost:4000/user/add HTTP/1.1
Content-Type: application/json

{

    "name": "dulamaa",
    "role": "user",
    "password": "123456",
    "email": "dulam@example.com",
    "contact": "99888766",
    "address_1": "chd 6 zanabazar st 46-78",
    "address_2": "",
    "user_image": "",
    "register_date": " 2023-03-05" 

}

### delete user

DELETE http://localhost:4000/user/delete/10002 HTTP/1.1


### delete product

DELETE http://localhost:4000/product/delete/4004 HTTP/1.1

   
### emps from morning
GET http://localhost:4000/employees?limit=3 HTTP/1.1

### brand add 
POST http://localhost:4000/brand/add HTTP/1.1
Content-Type: application/json

{
    "id":2000,
    "name": "Apple"
}

### category add 

POST http://localhost:4000/categories/add HTTP/1.1
Content-Type: application/json

{
    "id":1000 ,
    "name":"mobile device"
}

### spec add

POST http://localhost:4000/spec/add HTTP/1.1
Content-Type: application/json

{
    
    "id": 3000,
    "product_id": 4001,
    "property": "display",
    "values": "6.1 inches"

}